trigger:
  branches:
    include:
      - dev
      - master
  paths:
    include:
      - 'auth-api/'
      - 'users-api/'
      - 'todos-api/'
      - 'log-message-processor/'
      - 'frontend/'
      - 'k8s/'
      - 'azure-pipelines-app.yml'
    exclude:
      - '**/*.md'

pool:
  vmImage: ubuntu-latest

variables:
  # Determine environment based on branch
  - name: environment
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      value: 'prod'
    ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
      value: 'dev'
  - group: app-variables-${{ variables.environment }}

  # Define image names consistently
  - name: imageAuthApi
    value: 'auth-api'
  - name: imageUsersApi
    value: 'users-api'
  - name: imageTodosApi
    value: 'todos-api'
  - name: imageLogProcessor
    value: 'log-message-processor'
  - name: imageFrontend
    value: 'frontend'

  # Kubernetes details
  - name: k8sNamespace
    value: 'apps-$(environment)'
  - name: k8sRedisSecretName
    value: 'redis-secret'
  - name: k8sAppSecretName
    value: 'app-secrets'
  - name: k8sManifestPath
    value: 'k8s'

  # Service Connection Names
  - name: acrServiceConnection
    value: 'ACR-Service-Connection' # Replace
  - name: aksServiceConnection
    value: 'aks-prod-microAppProd-prod-pheasant-aks-apps-prod-1745099156012' # Replace

stages:
  # =========================================================================
  # Stage 1: Build and Push ONLY CHANGED Docker Images
  # =========================================================================
  - stage: BuildAndPush
    displayName: Build & Push Changed Images
    jobs:
      - job: BuildPushMatrix
        displayName: Build and Push Services
        strategy:
          matrix:
            AuthApi:
              imageName: $(imageAuthApi)
              buildContext: 'auth-api'
            UsersApi:
              imageName: $(imageUsersApi)
              buildContext: 'users-api'
            TodosApi:
              imageName: $(imageTodosApi)
              buildContext: 'todos-api'
            LogProcessor:
              imageName: $(imageLogProcessor)
              buildContext: 'log-message-processor'
            Frontend:
              imageName: $(imageFrontend)
              buildContext: 'frontend'
        steps:
          - checkout: self
            fetchDepth: 0
            displayName: Checkout Full History

          - task: Bash@3
            name: DetectChanges # Step name for output reference
            displayName: 'Detect Changes in $(buildContext)'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                SHOULD_BUILD="false"
                echo "Checking for changes in $(buildContext)/ between HEAD~1 and HEAD"
                if ! git diff --quiet HEAD~1 HEAD -- "$(Build.SourcesDirectory)/$(buildContext)/"; then
                  echo "Changes detected in $(buildContext). Setting SHOULD_BUILD=true."
                  SHOULD_BUILD="true"
                else
                  echo "No changes detected in $(buildContext)."
                fi
                # Set output variable for this job instance
                echo "##vso[task.setvariable variable=ShouldBuild;isOutput=true]$SHOULD_BUILD"

          - task: Docker@2
            displayName: 'Build and Push $(imageName) (if changed)'
            condition: eq(variables['DetectChanges.ShouldBuild'], 'true')
            inputs:
              containerRegistry: '$(acrServiceConnection)'
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/$(buildContext)/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/$(buildContext)'
              tags: '$(Build.BuildId)'
              addPipelineData: false

  # =========================================================================
  # Stage 2: Deploy to AKS
  # =========================================================================
  - stage: DeployToAKS
    displayName: Deploy Applications to AKS
    dependsOn: BuildAndPush
    condition: and(in(dependencies.BuildAndPush.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'), or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.SourceBranchName'], 'dev')))
    jobs:
      - deployment: DeployApps
        displayName: Deploy to AKS ($(environment))
        environment: 'aks-$(environment)'
        strategy:
          runOnce:
            deploy:
              steps:
                # STEP 0: Checkout
                - checkout: self
                  fetchDepth: 0
                  displayName: Checkout Repository

                # STEP 1: Debug K8s Directory Check
                - task: Bash@3
                  displayName: 'Debug: Check for K8s Manifests Directory'
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "Pipeline Workspace: $(Pipeline.Workspace)"
                      echo "Build Sources Directory: $(Build.SourcesDirectory)"
                      echo "Listing contents of $(Build.SourcesDirectory):"
                      ls -la $(Build.SourcesDirectory)
                      echo "Checking for $(Build.SourcesDirectory)/$(k8sManifestPath):"
                      if [ -d "$(Build.SourcesDirectory)/$(k8sManifestPath)" ]; then
                        echo "Directory $(Build.SourcesDirectory)/$(k8sManifestPath) found. Contents:"
                        ls -la "$(Build.SourcesDirectory)/$(k8sManifestPath)"
                      else
                        echo "ERROR: Directory $(Build.SourcesDirectory)/$(k8sManifestPath) NOT FOUND."
                        exit 1
                      fi

                # STEP 2: Replace Tokens
                - task: replacetokens@5
                  displayName: 'Replace Tokens in K8s Manifests'
                  inputs:
                    rootDirectory: '$(Build.SourcesDirectory)/$(k8sManifestPath)'
                    targetFiles: '**/*.yaml'
                    encoding: 'auto'
                    writeBOM: false
                    actionOnMissing: 'warn'
                    keepToken: false
                    tokenPrefix: '#{'
                    tokenSuffix: '}#'
                    useLegacyPattern: false
                    variables: |
                      k8sNamespace = $(k8sNamespace)
                      acrName = $(acrName)
                      Build.BuildId = $(Build.BuildId) # Still replace tag everywhere

                # STEP 3: Ensure Namespace exists
                - task: KubernetesManifest@0
                  displayName: Ensure Namespace $(k8sNamespace) exists
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    manifests: '$(Build.SourcesDirectory)/$(k8sManifestPath)/namespace.yaml'

                # STEP 4: Create/Update Secrets
                - task: KubernetesManifest@0
                  displayName: Create/Update Redis Secret ($(k8sRedisSecretName))
                  inputs:
                    action: 'createSecret'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    secretType: 'generic'
                    secretName: $(k8sRedisSecretName)
                    secretArguments: '--from-literal=redisHost=$(redisHostName) --from-literal=redisKey=$(redisPrimaryKey)'
                    force: true

                - task: KubernetesManifest@0
                  displayName: Create/Update App Secrets (JWT) ($(k8sAppSecretName))
                  inputs:
                    action: 'createSecret'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    secretType: 'generic'
                    secretName: $(k8sAppSecretName)
                    secretArguments: '--from-literal=jwtSecret=$(jwtSecretValue)'
                    force: true

                # STEP 5: Apply App ConfigMap
                - task: KubernetesManifest@0
                  displayName: Apply App ConfigMap
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: '$(Build.SourcesDirectory)/$(k8sManifestPath)/app-configmap.yaml'

                # --- UPDATED STEP: Prepare Deployment Flags (deploy only changed services) ---
                - task: Bash@3
                  name: PrepareDeployFlags
                  displayName: Prepare Deployment Flags
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "Preparing deployment flags..."
                      # Default flags to false
                      for svc in AuthApi UsersApi TodosApi LogProcessor Frontend; do
                        echo "##vso[task.setvariable variable=Deploy$svc]false"
                      done

                      # Correctly access output variables from the BuildAndPush stage
                      # Note: The job name 'BuildPushMatrix' and task name 'DetectChanges' are used.
                      # The matrix strategy generates job names like 'BuildPushMatrix_AuthApi'.
                      auth_built="$(dependencies.BuildAndPush.outputs['BuildPushMatrix_AuthApi.DetectChanges.ShouldBuild'])"
                      users_built="$(dependencies.BuildAndPush.outputs['BuildPushMatrix_UsersApi.DetectChanges.ShouldBuild'])"
                      todos_built="$(dependencies.BuildAndPush.outputs['BuildPushMatrix_TodosApi.DetectChanges.ShouldBuild'])"
                      logproc_built="$(dependencies.BuildAndPush.outputs['BuildPushMatrix_LogProcessor.DetectChanges.ShouldBuild'])"
                      frontend_built="$(dependencies.BuildAndPush.outputs['BuildPushMatrix_Frontend.DetectChanges.ShouldBuild'])"

                      echo "Build Flags: Auth=$auth_built, Users=$users_built, Todos=$todos_built, LogProc=$logproc_built, Frontend=$frontend_built"

                      # Set deploy flags for services with changes
                      [[ "$auth_built" == "true" ]] && echo "##vso[task.setvariable variable=DeployAuthApi]true"
                      [[ "$users_built" == "true" ]] && echo "##vso[task.setvariable variable=DeployUsersApi]true"
                      [[ "$todos_built" == "true" ]] && echo "##vso[task.setvariable variable=DeployTodosApi]true"
                      [[ "$logproc_built" == "true" ]] && echo "##vso[task.setvariable variable=DeployLogProcessor]true"
                      [[ "$frontend_built" == "true" ]] && echo "##vso[task.setvariable variable=DeployFrontend]true"

                # --- STEP 6: Conditional Service Deployments (Using simple variables) ---

                - task: KubernetesManifest@0
                  displayName: Apply Auth API Manifests (if changed or forced)
                  condition: eq(variables['DeployAuthApi'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/auth-api-deployment.yaml
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/auth-api-service.yaml

                - task: KubernetesManifest@0
                  displayName: Apply Users API Manifests (if changed or forced)
                  condition: eq(variables['DeployUsersApi'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/users-api-deployment.yaml
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/users-api-service.yaml

                - task: KubernetesManifest@0
                  displayName: Apply Todos API Manifests (if changed or forced)
                  condition: eq(variables['DeployTodosApi'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/todos-api-deployment.yaml
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/todos-api-service.yaml

                - task: KubernetesManifest@0
                  displayName: Apply Log Processor Manifests (if changed or forced)
                  condition: eq(variables['DeployLogProcessor'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/log-processor-deployment.yaml

                - task: KubernetesManifest@0
                  displayName: Apply Frontend Manifests (if changed or forced)
                  condition: eq(variables['DeployFrontend'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/frontend-deployment.yaml
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/frontend-service.yaml

                # STEP 7: Wait and List Resources via Kubectl@1
                - task: Kubectl@1
                  displayName: 'Wait for all deployments to become available'
                  condition: always()
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: '$(k8sNamespace)'
                    command: 'wait'
                    arguments: 'deployment --all --for=condition=available --timeout=300s'

                - task: Kubectl@1
                  displayName: 'List Deployments'
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: '$(k8sNamespace)'
                    command: 'get'
                    arguments: 'deployment'

                - task: Kubectl@1
                  displayName: 'List Pods'
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: '$(k8sNamespace)'
                    command: 'get'
                    arguments: 'pods -o wide'

                - task: Kubectl@1
                  displayName: 'List Services'
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: '$(k8sNamespace)'
                    command: 'get'
                    arguments: 'svc -o wide'

                # STEP 8: Additional Debugging for Failing Pods (If any)
                - task: Bash@3
                  displayName: 'Debug Failing Pods (if any)'
                  condition: always()
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "==== Checking for non-Running Pods in namespace $(k8sNamespace) ===="
                      FAILING_PODS=$(kubectl get pods -n $(k8sNamespace) --field-selector=status.phase!=Running -o name)
                      READY_BUT_NOT_RUNNING=$(kubectl get pods -n $(k8sNamespace) --field-selector=status.phase=Running -o jsonpath='{range .items[?(@.status.containerStatuses[*].ready==false)]}{.metadata.name}{"\n"}{end}')
                      ALL_ISSUES=$(echo "${FAILING_PODS}"$'\n'"${READY_BUT_NOT_RUNNING}" | grep . | sort -u)
                      if [ -z "$ALL_ISSUES" ]; then
                        echo "All pods appear to be Running and Ready."
                        exit 0
                      fi
                      echo "==== Describe and Log Pods with Issues ===="
                      echo "$ALL_ISSUES" | while IFS= read -r pod_resource_name; do
                        pod_name=${pod_resource_name#pod/}
                        echo ""
                        echo "---- Describing $pod_name ----"
                        kubectl describe pod $pod_name -n $(k8sNamespace) || echo "Failed to describe $pod_name"
                        echo ""
                        echo "---- Current Logs for $pod_name ----"
                        kubectl logs $pod_name -n $(k8sNamespace) --all-containers=true --tail=100 || echo "Failed to get current logs for $pod_name"
                        echo ""
                        echo "---- Previous Logs for $pod_name (if restarted) ----"
                        kubectl logs $pod_name -n $(k8sNamespace) --all-containers=true --previous --tail=100 || echo "No previous logs or failed to get previous logs for $pod_name"
                        echo "-------------------------------------"
                        echo ""
                      done
                      echo "Found pods with issues. See logs above."
                      exit 1