trigger:
  branches:
    include:
      - dev
      - master
  paths:
    include:
      - 'auth-api/'
      - 'users-api/'
      - 'todos-api/'
      - 'log-message-processor/'
      - 'frontend/'
      - 'k8s/'
      - 'azure-pipelines-app.yml'
    exclude:
      - '**/*.md'

pool:
  vmImage: ubuntu-latest

variables:
  # Determine environment based on branch
  - name: environment
    ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
      value: 'prod'
    ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
      value: 'dev'
  - group: app-variables-${{ variables.environment }} # Ensure 'acrName' is defined here

  # Define image names consistently
  - name: imageAuthApi
    value: 'auth-api'
  - name: imageUsersApi
    value: 'users-api'
  - name: imageTodosApi
    value: 'todos-api'
  - name: imageLogProcessor
    value: 'log-message-processor'
  - name: imageFrontend
    value: 'frontend'

  # Kubernetes details
  - name: k8sNamespace
    value: 'apps-$(environment)'
  - name: k8sRedisSecretName
    value: 'redis-secret'
  - name: k8sAppSecretName
    value: 'app-secrets'
  - name: k8sManifestPath
    value: 'k8s'

  # Service Connection Names
  - name: acrServiceConnection
    value: 'ACR-Service-Connection' # Replace if needed
  - name: aksServiceConnection
    value: 'aks-prod-microAppProd-prod-pheasant-aks-apps-prod-1745099156012' # Replace if needed

stages:
  # =========================================================================
  # Stage 1: Build and Push ONLY CHANGED Docker Images
  # =========================================================================
  - stage: BuildAndPush
    displayName: Build & Push Changed Images
    jobs:
      - job: BuildPushMatrix
        displayName: Build and Push Services
        strategy:
          matrix:
            AuthApi:
              imageName: $(imageAuthApi)
              buildContext: 'auth-api'
            UsersApi:
              imageName: $(imageUsersApi)
              buildContext: 'users-api'
            TodosApi:
              imageName: $(imageTodosApi)
              buildContext: 'todos-api'
            LogProcessor:
              imageName: $(imageLogProcessor)
              buildContext: 'log-message-processor'
            Frontend:
              imageName: $(imageFrontend)
              buildContext: 'frontend'
        steps:
          - checkout: self
            fetchDepth: 0 # Need history for git diff
            displayName: Checkout Full History

          - task: Bash@3
            name: DetectChanges # Step name for output reference
            displayName: 'Detect Changes in $(buildContext)'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                SHOULD_BUILD="false"
                # Compare against the previous commit on the same branch
                # Use origin/$BUILD_SOURCEBRANCHNAME to compare against the remote state before merge commit (if applicable)
                # Or use HEAD~1 for simpler direct parent comparison
                echo "Checking for changes in $(buildContext)/ between HEAD~1 and HEAD"
                # Use git diff with exit code check
                if ! git diff --quiet HEAD~1 HEAD -- "$(Build.SourcesDirectory)/$(buildContext)/"; then
                  echo "Changes detected in $(buildContext). Setting SHOULD_BUILD=true."
                  SHOULD_BUILD="true"
                else
                  echo "No changes detected in $(buildContext)."
                fi
                # Set output variable for this job instance
                echo "##vso[task.setvariable variable=ShouldBuild;isOutput=true]$SHOULD_BUILD"

          - task: Docker@2
            displayName: 'Build and Push $(imageName) (if changed)'
            # Use the output variable from the DetectChanges task IN THE SAME JOB
            condition: eq(variables['DetectChanges.ShouldBuild'], 'true')
            inputs:
              containerRegistry: '$(acrServiceConnection)'
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '$(Build.SourcesDirectory)/$(buildContext)/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)/$(buildContext)'
              tags: '$(Build.BuildId)'
              addPipelineData: false

  # =========================================================================
  # Stage 2: Deploy to AKS
  # =========================================================================
  - stage: DeployToAKS
    displayName: Deploy Applications to AKS
    dependsOn: BuildAndPush
    # Ensure stage runs only if BuildAndPush succeeded/skipped and branch is correct
    condition: and(in(dependencies.BuildAndPush.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'), or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.SourceBranchName'], 'dev')))
    jobs:
      - deployment: DeployApps
        displayName: Deploy to AKS ($(environment))
        environment: 'aks-$(environment)'
        strategy:
          runOnce:
            deploy:
              steps:
                # STEP 0: Checkout
                - checkout: self
                  # No need for fetchDepth here unless you need history in deploy stage
                  displayName: Checkout Repository

                # STEP 1: Debug K8s Directory Check (keep for verification)
                - task: Bash@3
                  displayName: 'Debug: Check for K8s Manifests Directory'
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "Pipeline Workspace: $(Pipeline.Workspace)"
                      echo "Build Sources Directory: $(Build.SourcesDirectory)"
                      echo "Listing contents of $(Build.SourcesDirectory):"
                      ls -la $(Build.SourcesDirectory)
                      echo "Checking for $(Build.SourcesDirectory)/$(k8sManifestPath):"
                      if [ -d "$(Build.SourcesDirectory)/$(k8sManifestPath)" ]; then
                        echo "Directory $(Build.SourcesDirectory)/$(k8sManifestPath) found. Contents:"
                        ls -la "$(Build.SourcesDirectory)/$(k8sManifestPath)"
                      else
                        echo "ERROR: Directory $(Build.SourcesDirectory)/$(k8sManifestPath) NOT FOUND."
                        exit 1
                      fi

                # STEP 2: Replace Tokens
                - task: replacetokens@5
                  displayName: 'Replace Tokens in K8s Manifests'
                  inputs:
                    rootDirectory: '$(Build.SourcesDirectory)/$(k8sManifestPath)'
                    targetFiles: '**/*.yaml'
                    encoding: 'auto'
                    writeBOM: false
                    actionOnMissing: 'warn'
                    keepToken: false
                    tokenPrefix: '#{'
                    tokenSuffix: '}#'
                    useLegacyPattern: false
                    variables: |
                      k8sNamespace = $(k8sNamespace)
                      acrName = $(acrName) # Ensure this is defined in your variable group
                      Build.BuildId = $(Build.BuildId) # Image tag

                # STEP 3: Ensure Namespace exists
                - task: KubernetesManifest@0
                  displayName: Ensure Namespace $(k8sNamespace) exists
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    manifests: '$(Build.SourcesDirectory)/$(k8sManifestPath)/namespace.yaml'

                # STEP 4: Create/Update Secrets
                - task: KubernetesManifest@0
                  displayName: Create/Update Redis Secret ($(k8sRedisSecretName))
                  inputs:
                    action: 'createSecret'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    secretType: 'generic'
                    secretName: $(k8sRedisSecretName)
                    secretArguments: '--from-literal=redisHost=$(redisHostName) --from-literal=redisKey=$(redisPrimaryKey)' # Ensure these vars are in the group
                    force: true

                - task: KubernetesManifest@0
                  displayName: Create/Update App Secrets (JWT) ($(k8sAppSecretName))
                  inputs:
                    action: 'createSecret'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    secretType: 'generic'
                    secretName: $(k8sAppSecretName)
                    secretArguments: '--from-literal=jwtSecret=$(jwtSecretValue)' # Ensure this var is in the group
                    force: true

                # STEP 5: Apply App ConfigMap
                - task: KubernetesManifest@0
                  displayName: Apply App ConfigMap
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: '$(Build.SourcesDirectory)/$(k8sManifestPath)/app-configmap.yaml'

                
                - task: Bash@3
                  name: PrepareDeployFlags
                  displayName: Prepare Deployment Flags
                  # Map the STAGE dependency outputs to environment variables for this task
                  env:
                    AUTH_BUILT: $[ stageDependencies.BuildAndPush.BuildPushMatrix.outputs['BuildPushMatrix_AuthApi.DetectChanges.ShouldBuild'] ]
                    USERS_BUILT: $[ stageDependencies.BuildAndPush.BuildPushMatrix.outputs['BuildPushMatrix_UsersApi.DetectChanges.ShouldBuild'] ]
                    TODOS_BUILT: $[ stageDependencies.BuildAndPush.BuildPushMatrix.outputs['BuildPushMatrix_TodosApi.DetectChanges.ShouldBuild'] ]
                    LOGPROC_BUILT: $[ stageDependencies.BuildAndPush.BuildPushMatrix.outputs['BuildPushMatrix_LogProcessor.DetectChanges.ShouldBuild'] ]
                    FRONTEND_BUILT: $[ stageDependencies.BuildAndPush.BuildPushMatrix.outputs['BuildPushMatrix_Frontend.DetectChanges.ShouldBuild'] ]
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "Preparing deployment flags..."
                      # Default flags to false
                      echo "##vso[task.setvariable variable=DeployAuthApi]false"
                      echo "##vso[task.setvariable variable=DeployUsersApi]false"
                      echo "##vso[task.setvariable variable=DeployTodosApi]false"
                      echo "##vso[task.setvariable variable=DeployLogProcessor]false"
                      echo "##vso[task.setvariable variable=DeployFrontend]false"

                      # Access the environment variables populated by the 'env:' block above
                      echo "Build Flags Read from Env: Auth='$AUTH_BUILT', Users='$USERS_BUILT', Todos='$TODOS_BUILT', LogProc='$LOGPROC_BUILT', Frontend='$FRONTEND_BUILT'"

                      # Use standard Bash comparison with the environment variables
                      if [[ "$AUTH_BUILT" == "true" ]]; then echo "##vso[task.setvariable variable=DeployAuthApi]true"; fi
                      if [[ "$USERS_BUILT" == "true" ]]; then echo "##vso[task.setvariable variable=DeployUsersApi]true"; fi
                      if [[ "$TODOS_BUILT" == "true" ]]; then echo "##vso[task.setvariable variable=DeployTodosApi]true"; fi
                      if [[ "$LOGPROC_BUILT" == "true" ]]; then echo "##vso[task.setvariable variable=DeployLogProcessor]true"; fi
                      if [[ "$FRONTEND_BUILT" == "true" ]]; then echo "##vso[task.setvariable variable=DeployFrontend]true"; fi

                      # Echo the VSO variables *after* they are set (using ADO macro syntax for logging)
                      echo "Deploy Flags Set: Auth=$(DeployAuthApi), Users=$(DeployUsersApi), Todos=$(DeployTodosApi), LogProc=$(DeployLogProcessor), Frontend=$(DeployFrontend)"

                      # Debugging with the environment variable
                      echo "DEBUG: Raw LOGPROC_BUILT env var value: |$LOGPROC_BUILT|"

                      if [[ "$LOGPROC_BUILT" == "true" ]]; then
                        echo "DEBUG: Setting DeployLogProcessor to true based on env var."
                      else
                        echo "DEBUG: Condition for DeployLogProcessor is FALSE. LOGPROC_BUILT env var was: |$LOGPROC_BUILT|"
                      fi

                # --- STEP 6: Conditional Service Deployments (using variables set above) ---

                - task: KubernetesManifest@1
                  displayName: Apply Auth API Manifests (if changed)
                  condition: eq(variables['DeployAuthApi'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/auth-api-deployment.yaml
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/auth-api-service.yaml

                - task: KubernetesManifest@1
                  displayName: Apply Users API Manifests (if changed)
                  condition: eq(variables['DeployUsersApi'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/users-api-deployment.yaml
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/users-api-service.yaml

                - task: KubernetesManifest@1
                  displayName: Apply Todos API Manifests (if changed)
                  condition: eq(variables['DeployTodosApi'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/todos-api-deployment.yaml
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/todos-api-service.yaml

                - task: KubernetesManifest@1
                  displayName: Apply Log Processor Manifests (if changed)
                  condition: eq(variables['DeployLogProcessor'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/log-processor-deployment.yaml # Assuming no service needed or it's separate

                - task: KubernetesManifest@1
                  displayName: Apply Frontend Manifests (if changed)
                  condition: eq(variables['DeployFrontend'], 'true')
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: '$(aksServiceConnection)'
                    namespace: $(k8sNamespace)
                    manifests: |
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/frontend-deployment.yaml
                      $(Build.SourcesDirectory)/$(k8sManifestPath)/frontend-service.yaml

                # --- FIXED STEP 7: Wait and List Resources via Kubernetes@1 ---
                - task: Kubernetes@1
                  displayName: 'Wait for all deployments to become available'
                  condition: always() # Run even if previous steps failed partially, to see the state
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: '$(aksServiceConnection)'
                    namespace: '$(k8sNamespace)'
                    command: 'wait'
                    # Correct syntax: kubectl wait <resource> --all --for=<condition>
                    arguments: 'deployment --all --for=condition=available --timeout=300s'
                    # Optional: Ignore exit code 1 if timeout occurs but you want pipeline to proceed
                    # ignoreReturnCode: true

                - task: Kubernetes@1
                  displayName: 'List Deployments'
                  condition: always()
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: '$(aksServiceConnection)'
                    namespace: '$(k8sNamespace)'
                    command: 'get'
                    arguments: 'deployment'

                - task: Kubernetes@1
                  displayName: 'List Pods'
                  condition: always()
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: '$(aksServiceConnection)'
                    namespace: '$(k8sNamespace)'
                    command: 'get'
                    arguments: 'pods -o wide'

                - task: Kubernetes@1
                  displayName: 'List Services'
                  condition: always()
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: '$(aksServiceConnection)'
                    namespace: '$(k8sNamespace)'
                    command: 'get'
                    arguments: 'svc -o wide'

                