apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
  namespace: #{k8sNamespace}#
spec:
  selector:
    app: auth-api # Selects pods with label 'app: auth-api'
  ports:
    - protocol: TCP
      port: 80 # Port the service is available on within the clusterxas
      targetPort: 8000 # Port the container listens on (AUTH_API_PORT)
  type: ClusterIP # Only reachable within the cluster