apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: #{k8sNamespace}#
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80 # Exposed port on the Load Balancer
      targetPort: 8080 # Port the container listens on (PORT)
  type: LoadBalancer # Creates an Azure Load Balancer for external access