apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor-deployment
  namespace: #{k8sNamespace}#
  labels:
    app: log-processor
spec:
  progressDeadlineSeconds: 300
  replicas: 1 # Can scale if processing becomes a bottlenecks
  selector:
    matchLabels:
      app: log-processor
  template:
    metadata:
      labels:
        app: log-processor
    spec:
      
      containers:
      - name: log-processor
        image: #{acrName}#.azurecr.io/#{imageLogProcessor}#:#{Build.BuildId}#
        env:
        - name: REDIS_HOST # Read from the 'redis-secret' secretsaxsaxfewdad
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redisHost
        - name: REDIS_PORT # Read from the ConfigMap
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_PORT
        - name: REDIS_CHANNEL # Read from the ConfigMap
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_CHANNEL
        
        - name: REDIS_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redisKey
      