apiVersion: v1
kind: Service
metadata:
  name: todos-api-service
  namespace: #{k8sNamespace}#
spec:
  selector:
    app: todos-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082 # Port the container listens on (TODO_API_PORT)
  type: ClusterIP