apiVersion: v1
kind: Service
metadata:
  name: users-api-service
  namespace: #{k8sNamespace}#
spec:
  selector:
    app: users-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083 # Port the container listens on (SERVER_PORT)sxa
  type: ClusterIP